"""add original title fields to titles

Revision ID: 4d338f920030
Revises: e991d20c5a87
Create Date: 2026-09-28 14:44:36.450749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d338f920030'
down_revision: Union[str, Sequence[str], None] = 'e991d20c5a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('original_title', sa.String(length=300), nullable=True))
    op.add_column('titles', sa.Column('english_name', sa.String(length=300), nullable=True))
    op.add_column('titles', sa.Column('original_language', sa.String(length=10), nullable=True))
    op.add_column('titles', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'tmdb_id')
    op.drop_column('titles', 'original_language')
    op.drop_column('titles', 'english_name')
    op.drop_column('titles', 'original_title')
    # ### end Alembic commands ###
